/// Test tuples whose fields can be generated by `rand::random`
use enum_derived::Rand;

const MAX_AGE: u8 = 120;

fn rand_age() -> RandomTypes {
    RandomTypes::Age(19)
}

fn rand_age_half() -> RandomTypes {
    RandomTypes::Age(5)
}

#[derive(Rand)]
pub enum RandomTypes {
    Empty,
    Boolean(bool),
    #[custom_rand(rand_age, rand_age_half)]
    Age(u8),
}

fn main() {}
